# This is the default configuration for the SPECTra-QMIX+ algorithm

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000 # 500000 for 6h_vs_8z

runner: "parallel"
batch_size_run: 8
buffer_size: 5000
batch_size: 128

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "custom_mac"
agent: "role_sep_rnn"
hidden_size: 64
rnn_hidden_size: 64
n_head: 4

# Optional flags
role_dim: 32
role_embed_add: False
role_kl_weight: 0.001
role_mi_weight: 0.01
role_diversity_weight: 0.005

# Loss parameters
# VAE
role_kl_beta: 5e-3
role_kl_warmup_steps: 10000
# Diversity
role_diversity: True
role_divserverity_weight: 5e-3
role_div_across_types_only: True
role_div_kernel_gamma: 2.0


agent_output_type: q

learner: "nq_role_learner"
mixer: "ss_mixer"

mixing_n_head: 4
hypernet_embed: 32

lr: 0.001 # Learning rate for agents
td_lambda: 0.6
optimizer: 'adam'
q_lambda: False

name: "role_kl_sep_qmix"

obs_agent_id: False # Include the agent's one_hot id in the observation
obs_last_action: False # Include the agent's last action (one_hot) in the observation